// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnpPNcEelKzCrn2Qme--p4RE2BDOlQMnc',
    appId: '1:271724865954:web:29134483dee4909c7f2afb',
    messagingSenderId: '271724865954',
    projectId: 'tourist-safety-app-aa6b3',
    authDomain: 'tourist-safety-app-aa6b3.firebaseapp.com',
    storageBucket: 'tourist-safety-app-aa6b3.firebasestorage.app',
    measurementId: 'G-014JY5JH1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQpA6jvJAdobhqUyzNO9fuDMJkijZ2ceg',
    appId: '1:271724865954:android:b762c36ed63fdf257f2afb',
    messagingSenderId: '271724865954',
    projectId: 'tourist-safety-app-aa6b3',
    storageBucket: 'tourist-safety-app-aa6b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjLtnUCyxOf9aImtQxnSAI-k-ztWeCAfQ',
    appId: '1:271724865954:ios:5cea0bba0866d4f37f2afb',
    messagingSenderId: '271724865954',
    projectId: 'tourist-safety-app-aa6b3',
    storageBucket: 'tourist-safety-app-aa6b3.firebasestorage.app',
    iosBundleId: 'com.example.touristSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjLtnUCyxOf9aImtQxnSAI-k-ztWeCAfQ',
    appId: '1:271724865954:ios:5cea0bba0866d4f37f2afb',
    messagingSenderId: '271724865954',
    projectId: 'tourist-safety-app-aa6b3',
    storageBucket: 'tourist-safety-app-aa6b3.firebasestorage.app',
    iosBundleId: 'com.example.touristSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnpPNcEelKzCrn2Qme--p4RE2BDOlQMnc',
    appId: '1:271724865954:web:7f0359800820cdf77f2afb',
    messagingSenderId: '271724865954',
    projectId: 'tourist-safety-app-aa6b3',
    authDomain: 'tourist-safety-app-aa6b3.firebaseapp.com',
    storageBucket: 'tourist-safety-app-aa6b3.firebasestorage.app',
    measurementId: 'G-GR0NLQ6DQZ',
  );
}
